version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    command:
      - --api
      - --api.insecure
      - --providers.docker
      - --providers.file.filename=/etc/ssl/traefik-tls.toml
      - --entrypoints.mongo.address=:27017
    ports:
      - "27017:27017"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../ssl:/etc/ssl

  mongo1:
    image: mongo:4.0
    hostname: mongo1.local
    restart: always
    labels:
      - "traefik.tcp.routers.mongo1.rule=HostSNI(`mongo1.local`)"
      - "traefik.tcp.routers.mongo1.tls=true"
      - "traefik.tcp.routers.mongo1.entrypoints=mongo"

  mongo2:
    image: mongo:4.0
    hostname: mongo2.local
    restart: always
    labels:
      - "traefik.tcp.routers.mongo2.rule=HostSNI(`mongo2.local`)"
      - "traefik.tcp.routers.mongo2.tls.passthrough=true"
      - "traefik.tcp.routers.mongo2.entrypoints=mongo"
    command:
      - "mongod"
      - "--sslMode=requireSSL"
      - "--sslPEMKeyFile=/etc/ssl/mongo.pem"
    volumes:
      - ../ssl:/etc/ssl
